# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: EB71C6BE-09D8-49D9-AEA0-446ADEC49F1F
publisher: dreamAviator
display_name: flatter
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
# setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - de
# Space-separated list of architecture identifiers the installer is allowed to run on.
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_architecturesallowed
# Defaults to `x64compatible` if not specified.
# architectures_allowed: x64compatible

# Space-separated list of architectures that should enable 64-bit install mode.
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_architecturesinstallin64bitmode
# Defaults to `x64compatible` if not specified.
# architectures_install_in_64bit_mode: x64compatible
